### ISSUE TITLE
plugin throws fatal error, why??

### ISSUE THREAD

**Issue by tommls** [simplifycom/woocommerce-simplify-payment-gateway-plugin#1]
Plugin could not be activated because it triggered a fatal error.
Fatal error: Cannot redeclare class WC_Gateway_Simplify_Commerce_Loader in /home/sdujyicb/public_html/wp-content/plugins/simplifycommerce/woocommerce-simplify-payment-gateway.php on line 25
Can not activate plugin, why???????????
Thank you, Tom
WP 4.7.5 and PHP 5.6.30
Had the old 1.0.4 Mike Jolley version installed, was trying to install new version.
Already had all API keys and whatnot entered into woocommerce payment settings section

**Comment by siddii** [comment]
Can you check if you have WooCommerce 2.6+ installed?

**Comment by tommls** [comment]
Version 3.0.7 woocommerce installed, thank you for asking.

**Comment by Johnnerz** [comment]
Hi Tom,

Just rewriting what we have discussed over email, you need to make sure the old plugin is disabled and uninstalled before you try to install this plugin, or else you will get these issues.

Kind Regards,
John
