### ISSUE TITLE
3D Secure Not Supported on Mobile?

### ISSUE THREAD

**Issue by SimoHDK** [simplifycom/woocommerce-simplify-payment-gateway-plugin#17]
Hi Team,

We seem to have an issue with 3D Secure on mobile, it simply does not load and displays an error as per attached. Is 3D secure supported on mobile? It works fine on Desktop.

![2](https://user-images.githubusercontent.com/17811281/70847716-a5f16600-1ebb-11ea-9f58-2baeaae9cf0e.PNG)
![1](https://user-images.githubusercontent.com/17811281/70847717-a5f16600-1ebb-11ea-9b8d-d49617ee49ae.PNG)

**Comment by AmeenJalali** [comment]
Same here. Please update the plugin!

**Comment by kennanseno** [comment]
hey @SimoHDK , apologies for the late(very) reply on this. I'm investigating this now but if you have more info on the transaction/merchant, that would be greatly appreciated!

**Comment by SimoHDK** [comment]
Hello, This was originally passed on via the CommBank simplify support teams. I can forward you the email trail if you inbox me your email address. Thanks!

**Comment by JohnbConneely** [comment]
Hi @SimoHDK we are actively looking into this issue and are able to reproduce. It is possibly an issue with the SDK being used and not specifically with the plugin, so it may take a bit longer to implement a fix.

Will update you when we have something in place

**Comment by AmeenJalali** [comment]
We have the same issue, please release an update! Please answer the comments and issues.

**Comment by JohnbConneely** [comment]
Hey @AmeenJalali @SimoHDK We released a change to the API on the 7th of July that should have solved this issue.

If it has not, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
