### ISSUE TITLE
Checkout Error

### ISSUE THREAD

**Issue by Luandrn** [simplifycom/woocommerce-simplify-payment-gateway-plugin#18]
Hi, I'm receiving the following error when I try to make a payment: An error has occurred
The redirect URL must be a valid endpoint on your website.

When I'm in test mode, the payment popup appears but in live mode I get the error above.

Any Advice?

**Comment by Luandrn** [comment]
Issue Resolved.

**Comment by SarahMN** [comment]
Hi Luandrn

how did you solve this issue?

**Comment by Luandrn** [comment]
Hi Sarah, to be honest, I've had so many issues I can't remember exactly how this one got resolved.
I know that the first problem was that the official plugin doesn't work. Ther's another one that I used and it fixed most issues.

**Comment by SimoHDK** [comment]
> Hi Sarah, to be honest, I've had so many issues I can't remember exactly how this one got resolved.
> I know that the first problem was that the official plugin doesn't work. Ther's another one that I used and it fixed most issues.

Are you able to advise what the 'other plugin' is?
