### ISSUE TITLE
Wocommerce Subscription Payments: Fatal Error

### ISSUE THREAD

**Issue by Luandrn** [simplifycom/woocommerce-simplify-payment-gateway-plugin#19]
Good morning

I'm Experiencing a fatal error on my WordPress site when trying to make a payment for a subscription-based product. I'm using Simplify 2.0.0 together with the latest version of Subscriptions (Woocommerce). See attached file for error code.

Any help would be appreciated.
![error](https://user-images.githubusercontent.com/15778962/73526742-8508b400-441a-11ea-9af3-c17972d807a2.JPG)

**Comment by JohnbConneely** [comment]
Hi @Luandrn ,

Are you using this plugin for subscriptions? https://woocommerce.com/products/woocommerce-subscriptions/

This is the subscriptions plugin we support to work with at the moment.

**Comment by JohnbConneely** [comment]
Hi @Luandrn ,

If you are still having an issue, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
