### ISSUE TITLE
Plugin Not Working 

### ISSUE THREAD

**Issue by SarahMN** [simplifycom/woocommerce-simplify-payment-gateway-plugin#23]
Hi

This plugin does not work correctly. When Our Customers want to pay, they at first encounter this error: Looks like something's not working. please try again and after they click on the OK button they see the payment modal. 

Do you know what this problem is?

![simplify error](https://user-images.githubusercontent.com/63838948/79542389-c8c99c00-80a0-11ea-94f3-49f4c40a5b7e.JPG)

**Comment by JohnbConneely** [comment]
Hey @SarahMN,
 
Is this on a macbook or Ipad?

We are aware of a similar issue on IOS and are actively investigating in order to get a fix out asap.

**Comment by anikitas** [comment]
Hello, is there any update on this issue?

**Comment by JohnbConneely** [comment]
Hey @anikitas, I believe this issue should be resolved in an update we pushed out at the end of July.

If it is not, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
