### ISSUE TITLE
Simplify doen't work with greek language

### ISSUE THREAD

**Issue by askgdb** [simplifycom/woocommerce-simplify-payment-gateway-plugin#24]
When a customer using greek characters in address and name details simplify doesn't approve the transaction. Although the details in the name field are in English, the transaction cannot be completed.
![2020-04-24 13 16 22](https://user-images.githubusercontent.com/17203298/80237811-02cd0c00-8666-11ea-9feb-9bd0cb7d6b57.jpg)

**Comment by wegeg** [comment]
same problem here!
when i change the billing details fields with the greek characters  the transaction approved except from address field which shows validation error and you have to change the characters to english.

**Comment by FlorinSTROIA** [comment]
Hello ! I have this error:

Error: Translation set not known in Simplify Commerce Payment Gateway for WooCommerce

http://prntscr.com/s98slk

Please help!

**Comment by nantoniadis** [comment]
I am having the same problem with the greek characters.

**Comment by cre8gr** [comment]
Same problem here with Greek characters. Should be fixed as it's not usable whatsoever.

**Comment by dntar** [comment]
I have the same problems with an integration and did some research. In the plugin's code I found the _woocommerce_simplify_commerce_hosted_args_ filter which can be used to modify the values just before they are used for the transaction. Thinking it was some other plugin corrupting the values, I tried this which DID NOT work:
```
add_filter('woocommerce_simplify_commerce_hosted_args', 'esimplify_fix_greek_chars', 10, 2);
function esimplify_fix_greek_chars($args, $order_id) {
    $args['address'] = htmlspecialchars_decode(html_entity_decode($args['address']));
    $args['address-city'] = htmlspecialchars_decode(html_entity_decode($args['address-city']));
    return $args;
}
```
Testing it some more, it seems the values are reaching the filter correctly. Then they are stored as data- attributes in the Pay Now button (still fine) and are sent to the server were the problem apparently begins. So I don't think it is a problem tied with this specific plugin.

My temporary solution was to alter the above code so it converts all characters to Greeklish (using a php function I found on github). Not a real solution probably, but will do for now.

**Comment by cre8gr** [comment]
> I have the same problems with an integration and did some research. In the plugin's code I found the _woocommerce_simplify_commerce_hosted_args_ filter which can be used to modify the values just before they are used for the transaction. Thinking it was some other plugin corrupting the values, I tried this which DID NOT work:
> 
> ```
> add_filter('woocommerce_simplify_commerce_hosted_args', 'esimplify_fix_greek_chars', 10, 2);
> function esimplify_fix_greek_chars($args, $order_id) {
>     $args['address'] = htmlspecialchars_decode(html_entity_decode($args['address']));
>     $args['address-city'] = htmlspecialchars_decode(html_entity_decode($args['address-city']));
>     return $args;
> }
> ```
> 
> Testing it some more, it seems the values are reaching the filter correctly. Then they are stored as data- attributes in the Pay Now button (still fine) and are sent to the server were the problem apparently begins. So I don't think it is a problem tied with this specific plugin.
> 
> My temporary solution was to alter the above code so it converts all characters to Greeklish (using a php function I found on github). Not a real solution probably, but will do for now.

Could you please share the code that changes characters to greeklish so at least we can use it for now untill there's a fix available?

**Comment by dntar** [comment]
Sure, pasting this in the theme's functions.php should work:
```
add_filter('woocommerce_simplify_commerce_hosted_args', 'esimplify_fix_greek_chars', 10, 2);
function esimplify_fix_greek_chars($args, $order_id) {
    $args['address'] = greek_latin_conv($args['address']);
    $args['address-city'] = greek_latin_conv($args['address-city']);
    return $args;
}

function greek_latin_conv($txt) {
    $greek = array('α','ά','Ά','Α','β','Β','γ','Γ','δ','Δ','ε','έ','Ε','Έ','ζ','Ζ','η','ή','Η','θ','Θ','ι','ί','ϊ','ΐ','Ι','Ί','κ','Κ','λ','Λ','μ','Μ','ν','Ν','ξ','Ξ','ο','ό','Ο','Ό','π','Π','ρ','Ρ','σ','ς','Σ','τ','Τ','υ','ύ','Υ','Ύ','φ','Φ','χ','Χ','ψ','Ψ','ω','ώ','Ω','Ώ');
    $latin = array('a','a','A','A','b','B','g','G','d','D','e','e','E','E','z','Z','i','i','I','th','Th','i','i','i','i','I','I','k','K','l','L','m','M','n','N','x','X','o','o','O','O','p','P','r','R','s','s','S','t','T','u','u','Y','Y','f','F','ch','Ch','ps','Ps','o','o','O','O');
    return str_replace($greek, $latin, $txt);
}
```
This translation function is very basic though, there are more accurate ones. But I believe it's suited for a quick workaround.

**Comment by JohnbConneely** [comment]
Hey @askgdb @dntar @cre8gr @nantoniadis @wegeg @FlorinSTROIA we have just released a new version of the plugin. It should solve this issue.

If your issue persists, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
