### ISSUE TITLE
Error: Translation set not known in Simplify Commerce Payment Gateway for WooCommerce

### ISSUE THREAD

**Issue by FlorinSTROIA** [simplifycom/woocommerce-simplify-payment-gateway-plugin#25]
Hello!

Please help! http://prntscr.com/s997bf

**Comment by JohnbConneely** [comment]
Hi @FlorinSTROIA we are aware of this issue and working on a fix.

**Comment by FlorinSTROIA** [comment]
Thanks!

**Comment by dzamanakos** [comment]
Hi, will you issue a fix soon? It's been a long time and cant translate the plugin strings.

**Comment by JohnbConneely** [comment]
Hey @FlorinSTROIA @dzamanakos  we have released a new version of the plugin. Please check if it solves your issue.

If your issue persists, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
