### ISSUE TITLE
Plugin showing an error

### ISSUE THREAD

**Issue by showponygraphics** [simplifycom/woocommerce-simplify-payment-gateway-plugin#27]
I am having the same issue as https://github.com/simplifycom/woocommerce-simplify-payment-gateway-plugin/issues/23
with the current version,
![Screen Shot 2020-06-30 at 5 43 22 pm](https://user-images.githubusercontent.com/67629196/86101433-99ea9000-bafd-11ea-8ac4-b5463cb2546a.png)

**Comment by JohnbConneely** [comment]
Hey @showponygraphics We made a change to your platform a couple of months back that should have resolved this issue. If it is still occurring could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
