### ISSUE TITLE
Order gets placed first Then Payment button is shown

### ISSUE THREAD

**Issue by lucid-developer** [simplifycom/woocommerce-simplify-payment-gateway-plugin#29]
Hi John,

I am using version 2.1.0 of the plugin. All my customer's order get placed first and move to pending payment status and then on the same page where order number is displayed comes a button to make payment. Now the payments are working fine. The issue is I want when customer click place order on checkout page, I want the hosted payment pop up to come first where the customer can add their card details and make payment. And only then the order should be created.

Is there a way to achieve this?

**Comment by JohnbConneely** [comment]
Hey @lucid-developer - We are looking into an enhancement where you will be able to use an embedded payment form which would hopefully reduce the amount of clicks to get to the card entry screen. We don't have a delivery date for this but if you could raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these as well as through the regular support route.
