### ISSUE TITLE
ID Called Incorrectly

### ISSUE THREAD

**Issue by captaincrank** [simplifycom/woocommerce-simplify-payment-gateway-plugin#4]
PHP 7 Error Log:
id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Simplify_Commerce->process_payment, WC_Gateway_Simplify_Commerce->process_standard_payments, WC_Gateway_Simplify_Commerce->do_payment, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.

Additionally, the plugin "support" and "docs" links lead to pages that state "This article doesn't have a translation for English"

Support Link: https://simplify.desk.com/customer/en/portal/articles/2639101-woocommerce-installation-guide

Docs Link: https://simplify.desk.com/customer/en/portal/articles/2639101-woocommerce-installation-guide

**Comment by alexanderkladov** [comment]
Noticed the same issue. I also got a similar error about billing email:

`billing_email was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Simplify_Commerce->process_payment, WC_Gateway_Simplify_Commerce->process_customer, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.`

Calling certain WC object properties directly like this `$order->id` or `$order->billing_email` is no longer allowed. Appropriate helper functions like this `$order->get_id()` or `$order->get_billing_email()` should be used instead.

So far, I can only see the following 2 files causing the problem:
1. /simplifycommerce/includes/class-subscription-addon.php
2. /simplifycommerce/includes/class-payment-gateway.php

I can see a lot of other lines that can potentially cause a problem in the future. All of these `$order->id`, `$order->order_total`, `$order->billing_address_1`, `$order->billing_address_2`, `$order->billing_city`, `$order->billing_state`, `$order->billing_postcode`, `$order->billing_country`, `$customer->id` should be updated to use their helper functions instead.

Can we get a ETA on the patch please?
